/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Darkmode: typeof import('./src/components/darkmode.vue')['default']
    Google: typeof import('./src/components/google.vue')['default']
    Headers: typeof import('./src/components/headers.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
  }
}
