/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Darkmode: typeof import('./src/components/darkmode.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
